// Digital book contents for reading
// Each book has multiple pages of content

export const bookContents: Record<string, string[]> = {
  "1": [ // The Midnight Library
    "Between life and death there is a library, and within that library, the shelves go on forever. Every book provides a chance to try another life you could have lived. To see how things would be if you had made other choices...\n\nWould you have done anything different, if you had the chance to undo your regrets?\n\nNora Seed finds herself faced with this decision. Faced with the possibility of changing her life for a new one, following a different career, undoing old breakups, realizing her dreams of becoming a glaciologist; she must search within herself as she travels through the Midnight Library to decide what is truly fulfilling in life, and what makes it worth living in the first place.",
    "Nineteen years before she decided to die, Nora Seed sat in the warmth of the small library at Hazeldene School in the town of Bedford.\n\nIt was lunchtime, and she had been sent there by Mrs Elm, the school librarian, after she'd been found crying by the climbing wall. She had grazed her knee, but that was not the cause of her tears.\n\n'You should never be ashamed of crying, Nora,' she told her.\n\n'It's not that, Miss. It's just… I don't think I've got any friends.'\n\n'Well, you have me. I am your friend.'\n\nNora smiled. The idea of a sixty-something librarian being a friend seemed a bit unlikely. But she appreciated the sentiment.",
    "Mrs Elm had run the library at Hazeldene School for years and lived in a little cottage on the grounds with her two cats. She was known for being kind and understanding to all students, especially the ones who felt a bit lost.\n\n'And you know what the best thing about this library is?' Mrs Elm asked, gesturing around at the shelves.\n\n'The books?'\n\n'Well, yes. But more specifically, the fact that every single book represents possibility. A chance to see the world differently, to live someone else's life, to understand perspectives you never would have considered otherwise.'\n\nNora nodded, wiping her eyes.\n\n'Books can be a shelter, Nora. They can be a refuge when the world feels too overwhelming.'",
    "Years later, Nora would remember this conversation as she found herself standing in the Midnight Library—a place that existed between life and death, where every book on every shelf represented a different life she could have lived.\n\nThe library was vast, infinite in ways that defied comprehension. The shelves stretched up into darkness, and the aisles seemed to go on forever. Each book was bound identically in green leather, and on each spine was written a title that represented a life choice.\n\n'The Book of Regrets' sat heavy on a pedestal near the entrance. Nora didn't want to open it, but she knew she had to. Inside were all the things she wished she had done differently, written in her own handwriting, page after page of what-ifs and should-haves.",
    "Mrs Elm appeared, looking exactly as she had all those years ago at Hazeldene School, before time and age had caught up with her in Nora's root life.\n\n'Hello, Nora,' she said warmly. 'Welcome to the Midnight Library.'\n\n'I don't understand,' Nora whispered. 'What is this place?'\n\n'This is the place between living and dying. And these books—they're all the lives you could have lived if you'd made different choices. Every decision you didn't make led to a different version of your life, and they're all here, waiting for you to experience them.'\n\nNora's heart raced. 'So I can live any life I want?'\n\n'You can try them,' Mrs Elm said. 'But you have to find the right one. The one that makes you want to stay alive.'",
  ],
  "2": [ // Atomic Habits
    "ATOMIC HABITS\nAn Easy & Proven Way to Build Good Habits & Break Bad Ones\n\nNo matter your goals, Atomic Habits offers a proven framework for improving—every day. James Clear, one of the world's leading experts on habit formation, reveals practical strategies that will teach you exactly how to form good habits, break bad ones, and master the tiny behaviors that lead to remarkable results.\n\nIf you're having trouble changing your habits, the problem isn't you. The problem is your system. Bad habits repeat themselves again and again not because you don't want to change, but because you have the wrong system for change.",
    "THE FUNDAMENTALS: WHY TINY CHANGES MAKE A BIG DIFFERENCE\n\n1% BETTER EVERY DAY\n\nIt is so easy to overestimate the importance of one defining moment and underestimate the value of making small improvements on a daily basis. Too often, we convince ourselves that massive success requires massive action.\n\nMeanwhile, improving by 1 percent isn't particularly notable—sometimes it isn't even noticeable—but it can be far more meaningful, especially in the long run. The difference a tiny improvement can make over time is astounding.",
    "Here's how the math works out: if you can get 1 percent better each day for one year, you'll end up thirty-seven times better by the time you're done. Conversely, if you get 1 percent worse each day for one year, you'll decline nearly down to zero. What starts as a small win or a minor setback accumulates into something much more.\n\nHabits are the compound interest of self-improvement. The same way that money multiplies through compound interest, the effects of your habits multiply as you repeat them. They seem to make little difference on any given day and yet the impact they deliver over the months and years can be enormous.",
    "THE FOUR LAWS OF BEHAVIOR CHANGE\n\nHow to Create a Good Habit:\n\nThe 1st Law (Cue): Make it obvious.\nThe 2nd Law (Craving): Make it attractive.\nThe 3rd Law (Response): Make it easy.\nThe 4th Law (Reward): Make it satisfying.\n\nHow to Break a Bad Habit:\n\nInversion of the 1st Law (Cue): Make it invisible.\nInversion of the 2nd Law (Craving): Make it unattractive.\nInversion of the 3rd Law (Response): Make it difficult.\nInversion of the 4th Law (Reward): Make it unsatisfying.\n\nThese four laws form the backbone of every habit. Understanding them will allow you to design habits that are easier to form and harder to break.",
    "THE 1ST LAW: MAKE IT OBVIOUS\n\nThe human brain is a prediction machine. It is continuously taking in your surroundings and analyzing the information it comes across. With enough practice, you can pick up on the cues that predict certain outcomes without consciously thinking about it.\n\nThis is how habits form. The process of behavior change always starts with awareness. You need to be aware of your habits before you can change them. The most effective way to do this is through a strategy called Habit Stacking.\n\nHabit stacking is a special form of an implementation intention. Rather than pairing your new habit with a particular time and location, you pair it with a current habit. The formula is: 'After [CURRENT HABIT], I will [NEW HABIT].'",
  ],
  "3": [ // Project Hail Mary
    "CHAPTER 1\n\n'What's two plus two?'\n\nSomething about the question irritates me. I'm not sure why. It's a perfectly reasonable question.\n\nBut for some reason, I want to say 'What's two plus two?' right back. Instead, I answer: 'Four.'\n\n'What's two plus two?'\n\n'Four.' I was right the first time, apparently. Why is he asking me the same thing again?\n\n'What is your name?'\n\nNow that's an interesting question. I'm sure I have a name. Obviously, I have a name. But what is it?",
    "I think hard. Really hard. The answer is there, somewhere in my mind. I know my name. Why can't I remember it?\n\n'I... I don't know.'\n\n'What is two plus two?'\n\n'Four.'\n\n'What is your name?'\n\nI still don't know. Why don't I know my own name? I know what a name is. I know that I have one. So why can't I think of it?\n\n'I don't know,' I say again.\n\nI hear a sigh. Where is it coming from? Where am I?\n\nI open my eyes. Or... I try to open my eyes. Are they already open? I can't tell. Either way, I don't see anything.",
    "After a moment, I realize there is something. The faintest of lights. Like a blurry, hazy glow in the distance. I concentrate on it. As I do, it becomes clearer. Sharper. I'm looking at... a ceiling? It's gray. There's a light source somewhere behind me casting illumination upward.\n\nOkay. I can see. That's progress.\n\n'What is two plus two?'\n\nI realize the question is coming from the ceiling. There's a speaker up there. Someone is talking to me through a speaker.\n\n'Four,' I say. My voice sounds hoarse and weak.\n\n'What is your name?'\n\n'I don't know.'",
    "Over time—I'm not sure how much time—I start to remember things. My name is Ryland Grace. I'm a scientist. I'm... somewhere. On a ship? Yes, a ship. A spaceship.\n\nBut why?\n\nThe memories come back in fragments, like pieces of a puzzle that don't quite fit together yet. I remember Earth. I remember a problem—a big problem. Something about the sun.\n\nThen it hits me all at once, a flood of memories that makes my head spin:\n\nThe sun is dying.\n\nNot just our sun—all the stars in the galaxy are losing energy. And if we don't figure out why and stop it, humanity will freeze to death in just a few decades.\n\nAnd I'm here, billions of miles from Earth, on a desperate mission to save the world.",
    "I float through the corridors of the Hail Mary, my spacecraft and home for what might be the rest of my life. The ship is designed for a three-person crew, but I'm alone. The other two crew members... they didn't make it. Their bodies lie in their dormancy chambers, victims of the same medical complications that should have killed me.\n\nBut I survived. I don't know why. Maybe sheer luck. Maybe my body chemistry was just different enough to handle the coma drugs.\n\nNow I have to complete the mission alone. I have to find the solution to the Astrophage—the microorganism that's eating the sun. And I have to get that solution back to Earth before it's too late.\n\nNo pressure.",
  ],
  "4": [ // The Song of Achilles
    "MY FATHER was a king and the son of kings. He was a short man, as most of us were, and built like a bull, all shoulders. He married my mother when she was fourteen and sworn by the priestess to produce only a single heir. I was that heir, born without fanfare in the middle of the night while my father held court.\n\nMy mother died before I was full-grown. I barely remember her. What I recall is not her face, but the way the light would slant through our home's windows, gilding her dark hair. I remember that she smelled like earth after rain.\n\nMy father did not mourn her. Within the year he married again, and then again after that. He was prolific in his appetites, my father, and his halls echoed with the screams of serving women whom he visited at night.",
    "I was five when I first saw the boy. He was younger than me, and small for his age. His hair was the color of autumn leaves, a red-gold that seemed to catch fire in the sun. Everything about him seemed to move—his limbs, his face, even his hair.\n\nHe had been sent to our court by his father, just as other boys had been sent before him. It was the custom then, for kings to foster each other's sons, creating bonds between kingdoms. Most of the boys were older, already training with swords and spears. But this boy was young, perhaps only four years old.\n\nI watched him from across the courtyard as he stood beside his father. He did not cry or cling. He simply observed everything with bright, curious eyes.",
    "That night, during the feast, I saw him again. He sat at a table with the other foster boys, but he did not join in their games or conversation. Instead, he sat quietly, his eyes tracking the movements of everyone in the hall.\n\nMy father stood to make his announcement. 'This is Achilles, son of Peleus and the sea-nymph Thetis. He will train here, among our finest warriors.'\n\nThe name meant nothing to me then. I did not know that it would come to mean everything.\n\nThe boy—Achilles—met my gaze across the hall. For a moment, our eyes locked. Then he smiled, a quick bright thing, and returned to his food.",
    "In the days that followed, I found myself drawn to him. There was something about Achilles that was different from the other boys. He moved with a grace that seemed impossible, as if gravity affected him differently. He could run faster, jump higher, and fight better than anyone else.\n\nBut it wasn't just his physical abilities that fascinated me. It was the way he seemed to exist in his own world, untouched by the pettiness and cruelty that surrounded us. While the other boys jostled for position and favor, Achilles remained serene, confident in his own worth.\n\nI wanted to be near him. I wanted to understand him. And so I watched, and waited, and hoped that one day he might notice me again.",
    "The day came sooner than I expected. I was practicing my forms in the training yard when Achilles approached. He had been watching me, he said, and he thought I might benefit from some instruction.\n\nI was humiliated. Here was this boy, younger and smaller than me, offering to teach me as if I were some kind of inferior.\n\nBut then he smiled, and something in his expression made me reconsider. This wasn't mockery. It was genuine kindness.\n\n'Show me,' I said.\n\nAnd he did. He showed me how to move, how to balance, how to make my body do things I had never thought possible. And as we trained together, something shifted between us. A connection formed, delicate as spider silk but strong as iron.\n\nThis was the beginning of everything.",
  ],
  "5": [ // Sapiens
    "PART ONE: THE COGNITIVE REVOLUTION\n\n1. AN ANIMAL OF NO SIGNIFICANCE\n\nAbout 13.5 billion years ago, matter, energy, time and space came into being in what is known as the Big Bang. The story of these fundamental features of our universe is called physics.\n\nAbout 300,000 years after their appearance, matter and energy started to coalesce into complex structures, called atoms, which then combined into molecules. The story of atoms, molecules and their interactions is called chemistry.\n\nAbout 3.8 billion years ago, on a planet called Earth, certain molecules combined to form particularly large and intricate structures called organisms. The story of organisms is called biology.",
    "About 70,000 years ago, organisms belonging to the species Homo sapiens started to form even more elaborate structures called cultures. The subsequent development of these human cultures is called history.\n\nThree important revolutions shaped the course of history: the Cognitive Revolution kick-started history about 70,000 years ago. The Agricultural Revolution sped it up about 12,000 years ago. The Scientific Revolution, which got under way only 500 years ago, may well end history and start something completely different.\n\nThis book tells the story of how these three revolutions have affected humans and their fellow organisms.\n\nWere we destined to become the masters of the planet? Or was it just a lucky accident?",
    "Humans first evolved in East Africa about 2.5 million years ago from an earlier genus of apes called Australopithecus, which means 'Southern Ape'. About 2 million years ago, some of these archaic men and women left their homeland to journey through and settle vast areas of North Africa, Europe and Asia.\n\nSince survival in the snowy forests of northern Europe required different traits than those needed to stay alive in Indonesia's steaming jungles, human populations evolved in different directions. The result was several distinct species, each uniquely adapted to its environment.\n\nEuropeans evolved into Homo neanderthalensis – 'Man from the Neander Valley' – or simply, Neanderthals. The more eastern regions of Asia were populated by Homo erectus, 'Upright Man'. In Indonesia lived Homo soloensis, 'Man from the Solo Valley'.",
    "For countless generations, humans of all species lived relatively simple lives. They hunted animals and gathered plants, moving from place to place in small bands. They had fire and stone tools. They had language and art. But they had no cities, no writing, no agriculture.\n\nThen, about 70,000 years ago, Homo sapiens started doing very special things. They began creating boats that enabled them to reach and settle Australia. They invented oil lamps that lit up caves and enabled humans to paint the amazing Lascaux and Chauvet paintings. They created the first needles, essential for making warm clothing and thus enabling humans to survive in the freezing tundra of the Ice Age.\n\nWhat happened? How did Homo sapiens suddenly become so much more capable?",
    "The answer is the Cognitive Revolution. Between 70,000 and 30,000 years ago, Homo sapiens developed new ways of thinking and communicating. This is what we call the Cognitive Revolution.\n\nThe appearance of new ways of thinking and communicating, between 70,000 and 30,000 years ago, constitutes the Cognitive Revolution. What caused it? We're not sure. The most commonly believed theory argues that accidental genetic mutations changed the inner wiring of the brains of Sapiens, enabling them to think in unprecedented ways and to communicate using an altogether new type of language.\n\nThis is the Tree of Knowledge mutation. Why did it occur in Sapiens DNA rather than in that of Neanderthals? It was a matter of pure chance.",
  ],
  "6": [ // The Seven Husbands of Evelyn Hugo
    "EVELYN HUGO FINALLY READY TO REVEAL ALL\n\nAging and reclusive Hollywood movie icon Evelyn Hugo is finally ready to tell the truth about her glamorous and scandalous life. But when she chooses unknown magazine reporter Monique Grant for the job, no one is more astounded than Monique herself. Why her?\n\nMonique is not exactly on top of the world. Her husband has left her, and her career has stagnated. Regardless of why Evelyn has selected her, Monique is determined to use this opportunity to jumpstart her career.\n\nSummoned to Evelyn's luxurious apartment, Monique listens in fascination as the actress tells her story. From making her way to Los Angeles in the 1950s to her decision to leave show business in the '80s, and, of course, the seven husbands along the way, Evelyn unspools a tale of ruthless ambition, unexpected friendship, and a great forbidden love.",
    "I'm sitting in Evelyn Hugo's living room, on a white sofa so pristine I'm afraid to move. The apartment is on the Upper East Side, in a building with a doorman who called upstairs before letting me in. Everything about this place screams old money and good taste.\n\nEvelyn herself is exactly as I'd imagined and nothing like I expected. At seventy-nine, she's still breathtakingly beautiful, her bone structure as sharp and elegant as it was in her heyday. But there's something fragile about her now, something that wasn't there in the movies.\n\n'You're probably wondering why I chose you,' she says, her voice still carrying that distinctive husky quality that made her famous.\n\nI nod. I've been wondering nothing else since I got the call.\n\n'I'll tell you,' she says. 'But first, let me tell you about my first husband.'",
    "ERNIE DIAZ: 1952-1953\n\nI was seventeen when I met Ernie Diaz, and I was nobody. I'd just arrived in Los Angeles with nothing but a suitcase and a dream that probably a million other girls had before me.\n\nErnie was a nobody too, but he was a nobody who knew people. He worked as a grip on movie sets, and he had connections. More importantly, he was willing to marry me so I could get my name changed legally without my family's permission.\n\nYou see, Evelyn Hugo wasn't my real name. I was born Evelyn Elena Herrera, a poor Cuban girl from Hell's Kitchen. But Hollywood in the 1950s wasn't kind to girls with Spanish surnames. So I needed a new name, and Ernie needed a wife to make his mother happy.\n\nIt was a business arrangement, pure and simple. We got married at City Hall, and we were divorced before our first anniversary. But Ernie gave me something valuable: a new identity and my first real introduction to the movie business.",
    "DON ADLER: 1954-1956\n\nDon Adler was already a star when I met him. He was handsome, charming, and completely wrong for me. But he was also my ticket to real fame, and I knew it.\n\nOur marriage made headlines. America's Golden Boy and the Rising Starlet. We were on the cover of every magazine. The studio loved us together.\n\nWhat the magazines didn't know was that Don had a temper. Behind closed doors, away from the cameras and the fans, he was a different person. He drank too much, and when he drank, he became cruel.\n\nI stayed with him for two years, playing the role of the devoted wife while my own star continued to rise. When I finally left him, I made sure everyone knew why. It was a scandal, yes, but it was also the end of Don Adler's career and the real beginning of mine.",
    "MAX GIRARD: 1957-1958\n\nMax was different. Max was kind. After Don, I needed kindness more than I needed air.\n\nHe was a producer, older than me by twenty years, and he treated me like I was precious. He never raised his voice. He never raised his hand. He simply loved me, in his quiet, steady way.\n\nI tried to love him back. I really did. But the truth was, I was incapable of loving him the way he deserved. My heart belonged to someone else, even then.\n\nWe divorced amicably after a year. Max went on to marry someone who could love him properly, and I went on to make the biggest mistake of my life: I married for publicity instead of for love, over and over again.\n\nBut that comes later in the story.",
  ],
  "7": [ // Educated
    "PROLOGUE\n\nMy strongest memory is not a memory. It's something I imagined, then came to remember as if it had happened. The memory was formed when I was five, just before I turned six, from a story my father told in such detail that I and my brothers and sister had each conjured our own cinematic version, with gunfire and shouts. Mine had crickets. That's the only difference. In my memory it's always summer, and my father is always standing near the kitchen window, a light, warm wind blowing across the fields.\n\nThe story was about the Weavers, a family my father said had been persecuted by the government.",
    "I'm standing in the kitchen, listening to my father tell the story. My mother is silent, her eyes fixed on a distant point outside the window. My brothers are there too, listening with rapt attention.\n\n'They came with tanks and guns,' Dad says, his voice low and urgent. 'Surrounded the house. Randy Weaver was just defending his family, and they shot his son. Then they shot his wife while she was holding a baby.'\n\nI don't understand everything he's saying, but I understand the fear in his voice. I understand that the government is dangerous, that they can come for you even when you've done nothing wrong.\n\nThis story, and others like it, would shape my entire childhood.",
    "PART ONE\n\nCHAPTER 1: CHOOSE THE GOOD\n\nMy childhood was a preparation for the End of Days. The exact nature of the disaster, whether it would be war, famine, or plague, we couldn't know. But we could prepare.\n\nDad built a root cellar in our basement, where we stored hundreds of pounds of wheat, rice, and beans. We had barrels of honey, cases of powdered milk, and enough ammunition to hold off an army.\n\nMy mother was an herbalist and midwife, gathering wild herbs and mixing tinctures to treat everything from cuts to cancer. She never took us to doctors. Doctors were part of the government's conspiracy, she said. They would fill us with vaccines and chemicals designed to control our minds.",
    "I was nine the first time I questioned this worldview. It happened in the scrap yard where my father worked, turning wrecked cars into salvaged metal.\n\nI was helping sort copper from aluminum when a piece of metal sliced through my leg, cutting deep. Blood poured from the wound, but Dad just wrapped it in a rag and told me to keep working.\n\n'It'll heal,' he said. 'Your body knows what to do.'\n\nIt did heal, eventually, but it left a scar that I carry to this day. A reminder of the price of my father's beliefs.",
    "Years passed. I worked in the scrap yard. I helped my mother make tinctures. I learned to can peaches and rotate food storage. I prepared for the End of Days.\n\nBut something was changing inside me. I started to wonder about the world beyond Buck's Peak, the mountain where we lived. I wondered about school, about books, about all the things my father said were corrupting and evil.\n\nWhen I was sixteen, I did something that changed my life: I taught myself enough math to take the ACT. And when I passed, when I got into Brigham Young University, I stepped out of one world and into another.\n\nThis is the story of that journey. The story of how I left Buck's Peak and found education. The story of how I became, finally, myself.",
  ],
  "8": [ // The Invisible Life of Addie LaRue
    "New York City\nMarch 15, 2014\n\nA girl falls into the Hudson River.\n\nIt is the first of March, and the water is numbingly cold, the current swift and strong. She does not know how to swim. She does not try. The water closes over her head, and she sinks like a stone.\n\nThis is not how Addie LaRue dies.\n\n(Because Addie LaRue cannot die.)\n\nThis is simply how she falls in love.\n\nBut first, a word on the nature of such things. Love is complicated. It is not always clear, not always pure. Sometimes it is painful, and sometimes it is worth the pain. And sometimes, just sometimes, it is both eternal and impossible.",
    "Villon-sur-Sarthe, France\nJuly 29, 1714\n\nAdeline LaRue is born in the winter of 1691, in a small village in France that doesn't appear on most maps. She is the only child of a wood carver and his wife, and from the day she can walk, she is different.\n\nWhere other children are content to stay within the bounds of the village, Addie always wanders. She explores the woods, climbs trees, and returns home with torn skirts and tangled hair, earning her mother's disapproval and her father's quiet smile.\n\n'She has too much freedom,' her mother says.\n\n'She has just enough,' her father replies.",
    "On the day before her twenty-fourth birthday, Adeline is to be married. It is a good match, everyone says. Roger is a widower with three young children who need a mother. He owns a house in the village and has a steady trade as a butcher.\n\nAdeline does not love him. She has never loved anyone, not in that way. Her heart belongs to the world beyond Villon, to the places she has never seen and the adventures she will never have.\n\nBecause once she marries Roger, her life will be decided. She will be a wife, a mother, a keeper of house and home. The woods she loves will become distant memories, replaced by the smell of cooking meat and the sound of children crying.\n\nShe cannot bear it.",
    "As the sun sets on July 29, 1714, Adeline runs into the woods. She finds the old shrine, the one the villagers have long since abandoned for the church in town. She kneels before the altar, and she prays.\n\nBut she does not pray to God. She prays to the gods of the woods, the old gods her grandmother spoke of in whispers. She prays for freedom, for time, for a life that will not be forgotten.\n\n'Please,' she whispers. 'I don't want to belong to anyone but myself. I don't want to fade away and be forgotten. Let me live. Let me be free. Give me time.'\n\nThe darkness answers.\n\nA voice like smoke and shadow speaks: 'Are you certain?'\n\n'Yes,' Addie says, not knowing what she has just agreed to.",
    "The bargain is made. Addie LaRue will live forever. She will never age, never sicken, never die. She will have all the time in the world to see everything, to do everything, to be everything.\n\nBut there is a price.\n\nNo one will remember her. As soon as she leaves someone's sight, she will fade from their memory like a dream upon waking. She can make no mark on the world. She cannot write her name, cannot take a photograph, cannot leave any trace of her existence.\n\nShe will be invisible in the worst possible way—not unseen, but unforgettable.\n\nAnd so begins the invisible life of Addie LaRue, a life that will span three centuries and change everything she thought she knew about love, time, and what it means to be remembered.",
  ],
  "9": [ // Where the Crawdads Sing
    "PART ONE: THE MARSH\n\n1. THE SHACK\n1952\n\nThe morning burned so August-hot, the marsh's moist breath hung the oaks and pines with fog. The palmetto patches stood unusually quiet except for the low, slow flap of the heron's wings lifting from the lagoon. And then, Kya, only six years old, heard the screen door slap. Standing on the stool, she stopped scrubbing grits from the pot and lowered it into the basin of worn-out suds. No sounds now but her own breathing. Who had left? Not Ma. She never let the door slam.",
    "Kya waited. The tiny shack was quiet. She touched her thin fingers to her chest, feeling her heart thump. Ma's not home. Ma's gone. She felt the words more than thought them.\n\nFor the next few hours, Kya watched from the front steps as the sun cut through the fog, bright and clean. Surely, Ma would return by afternoon. But when the sun was high and hot, and Ma still had not appeared, Kya walked into the woods.\n\nThe marsh was her friend. It had raised her as much as Ma had. She knew every bird call, every plant, every creature that lived in the brackish water and the thick mud. The marsh didn't judge her. It didn't leave.",
    "Days turned into weeks. Ma did not return. Kya's older siblings left one by one, unable or unwilling to stay in the shack with Pa, who drank and raged and filled the small space with violence.\n\nEventually, it was just Kya and Pa. And then, one day, it was just Kya.\n\nShe was seven years old, alone in the marsh, with no one to teach her, no one to care for her, no one to notice if she lived or died.\n\nBut Kya survived. She learned to fish and dig for mussels. She learned which plants were edible and which would make her sick. She learned to read the tides and the weather. She learned to be alone.",
    "The people of Barkley Cove called her the Marsh Girl. They whispered about her when she came to town to trade mussels for grits and lard. They pointed and stared and kept their children away from her.\n\nKya didn't mind. She had the marsh, and the marsh was enough.\n\nBut deep inside, in a place she wouldn't acknowledge even to herself, she was lonely. She watched the gulls fly in pairs and the deer walk with their fawns, and she wondered what it would be like to belong to someone, to have someone belong to her.",
    "Then one day, a boy came into her life. Tate was older than her by a few years, tall and lanky with kind eyes. He taught her to read, brought her books, showed her the world beyond the marsh.\n\nFor the first time in her life, Kya felt seen. Not as the Marsh Girl, but as herself. As someone worthy of kindness and attention and love.\n\nBut love, as Kya would learn, is complicated. It can save you or destroy you, lift you up or tear you down. And in the marsh, where beauty and danger exist side by side, love is the most dangerous thing of all.",
  ],
  "10": [ // The Psychology of Money
    "INTRODUCTION: The Greatest Show On Earth\n\nAn idea that will change your life:\n\nYour personal experiences with money make up maybe 0.00000001% of what's happened in the world, but maybe 80% of how you think the world works.\n\nLike everything else in life, money—how people earn it, save it, spend it, and think about it—is a product of experiences and circumstances that vary wildly from person to person. And those experiences are not equally distributed throughout society.\n\nYour lifetime of financial experience is likely to be fundamentally different from mine, which is likely to be fundamentally different from the next person's.",
    "We all think we know how money works. But do we really?\n\nDoing well with money isn't necessarily about what you know. It's about how you behave. And behavior is hard to teach, even to really smart people.\n\nA genius who loses control of their emotions can be a financial disaster. The opposite is also true. Ordinary folks with no financial education can be wealthy if they have a handful of behavioral skills that have nothing to do with formal measures of intelligence.\n\nMy favorite Wikipedia entry begins: 'Ronald James Read was an American philanthropist, investor, janitor, and gas station attendant.'",
    "Ronald Read was born in rural Vermont. He was the first person in his family to graduate high school. He spent his career as a janitor and a gas station attendant. He died in 2014 at age 92.\n\nHere's the remarkable part: When his will was revealed, it turned out that Ronald Read had amassed an $8 million fortune. He left $2 million to his stepchildren and $6 million to his local hospital and library.\n\nHow did a janitor accumulate $8 million? He invested his savings in blue-chip stocks and held them for decades. He lived frugally, never flaunted his wealth, and let compound interest do its work.",
    "Compare Ronald Read to Richard Fuscone. Fuscone was everything Ronald Read was not. He had a Harvard MBA and became a vice chairman at Merrill Lynch. He earned millions in his career and lived in a 18,000-square-foot home in Greenwich, Connecticut.\n\nIn 2008, Richard Fuscone declared bankruptcy. His home was foreclosed. His wealth evaporated.\n\nWhat happened? He borrowed too much. He spent too much. He assumed his high income would continue forever, and when it didn't, he had no buffer, no safety net.\n\nThe difference between Ronald Read and Richard Fuscone is not intelligence. It's behavior. It's temperament. It's the ability to delay gratification and think long-term.",
    "This book is about those soft skills. The behaviors and mindsets that determine financial success.\n\nBecause the truth is, financial success is not a hard science. It's a soft skill where how you behave is more important than what you know.\n\nI'll share 20 short stories that explore these ideas:\n\n1. No One's Crazy\n2. Luck & Risk  \n3. Never Enough\n4. Confounding Compounding\n5. Getting Wealthy vs. Staying Wealthy\n\nAnd 15 more lessons that will change how you think about money, wealth, and what it means to live a good life.\n\nLet's begin.",
  ],
};
